//! Byte-exact encoders and decoders for what the C firmware keeps in NVS, so the Rust firmware reads (and later writes) the same flash.
//!
//! A device flashed alternately with the C and the Rust image shares its NVS, so every layout here is the natural-alignment
//! little-endian layout of the corresponding C struct on xtensa (sizes and offsets are asserted in the tests and checked against a host C
//! build). The crate is pure: `no_std`, no allocation, no unsafe code, no ESP-IDF types.
//!
//! | NVS key | Module | Blob |
//! |---|---|---|
//! | `tn_settings/wifi_profiles` | [`wifi_profiles`] | 784 bytes: SSIDs and passwords |
//! | `tn_settings/wifi_meta` | [`wifi_meta`] | 516 bytes: names, priorities, preferred network, keyed by SSID |
//! | `tn_settings/display` | [`ui_settings`] | 8 bytes |
//! | `tn_settings/mode` | [`mode`] | one `u8` |
//! | `adapter/config` (v0.1.x, read only) | [`legacy`] | 1004 bytes |
//!
//! [`load`] combines them the way `wifi_load_profiles()` does at boot, and [`profile_json`] is the `profile` command's parser.
//! Golden blobs generated by the real C code live in `tests/golden` (`tools/regen.sh`).

#![no_std]
#![forbid(unsafe_code)]

pub mod cstr;
pub mod legacy;
pub mod load;
pub mod metadata_json;
pub mod mode;
pub mod profile_json;
pub mod ui_settings;
pub mod wifi_meta;
pub mod wifi_profiles;
