//! The one-line JSON profile command shared by the serial console and the setup page.
//!
//! Port of `main/profile_json.c` (`profile_parse_json`, tested by `tests/test_profile_json.c`). The C code runs cJSON 1.7.19 (ESP-IDF
//! v5.5.5) and then a handful of checks; this port reproduces the *accepted language* of that combination without allocating, quirks
//! included, and `tests/golden/json_corpus.bin` (generated by the real C parser) pins it:
//!
//! * the text is a C string: it ends at the first NUL byte, and is refused above 500 bytes or when a backslash is followed by `u` or by the
//!   end (so no `\uXXXX` escape, hence no embedded NUL);
//! * one leading UTF-8 BOM is skipped (when the text is at least 4 bytes); whitespace is *any* byte up to 0x20; nothing but whitespace may
//!   follow the object;
//! * the root is an object with exactly the five keys `slot`, `priority`, `name`, `ssid`, `password`, each once, in any order, with a number
//!   for `slot` and `priority` and a string for the others; a value of any other JSON type, an unknown key or a duplicate is refused;
//! * a number is what C `strtod` reads from a run of `0-9 + - e E .` that starts with `-` or a digit, so `1.0`, `1e0`, `01`, `1.` and `-0` are
//!   all numbers; it must be an exact integer once converted to `f64` (`1.00000000000000000001` rounds to 1 and is accepted); the range is
//!   1 to 8 for `slot` and 0 to 100 for `priority`;
//! * strings may contain raw control and high bytes (cJSON does not object) and the escapes `\" \\ \/ \b \f \n \r \t`; the decoded name,
//!   SSID and password must then pass [`LegacyProfile::valid`] (printable ASCII, 1 to 24 / 1 to 32 characters, password empty or 8 to 63).
//!
//! Failure details differ from C only in which rule is reported first; the accept/reject decision is the same.

use crate::cstr::c_str;
use crate::legacy::LegacyProfile;
use core::str::FromStr;

/// Longest accepted text (C `strlen(json) > 500` is refused).
pub const MAX_LEN: usize = 500;

const KEY_SLOT: u8 = 1;
const KEY_PRIORITY: u8 = 2;
const KEY_NAME: u8 = 4;
const KEY_SSID: u8 = 8;
const KEY_PASSWORD: u8 = 16;
const ALL_KEYS: u8 = 31;

/// Why a profile command is refused (C `profile_parse_json` returning false).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ProfileJsonError {
    /// More than [`MAX_LEN`] bytes.
    TooLong,
    /// A backslash followed by `u` or by the end of the text.
    EscapeNotAllowed,
    /// Not the JSON object this command takes (syntax, wrong root type, bad escape, a value that is neither string nor number).
    Malformed,
    /// A key that is not one of the five, or one given twice.
    BadKey,
    /// One of the five keys is missing.
    MissingKey,
    /// A number that is not an integer in range, or a string longer than its field.
    BadValue,
    /// The profile fields fail [`LegacyProfile::valid`].
    InvalidProfile,
}

/// A parsed command: the 0-based slot (the text says 1 to 8) and the profile.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct ParsedProfile {
    /// Slot index, 0 to 7.
    pub slot: usize,
    /// The profile; always passes [`LegacyProfile::valid`].
    pub profile: LegacyProfile,
}

/// A byte cursor over the text with cJSON's whitespace rule.
struct Cursor<'a> {
    text: &'a [u8],
    at: usize,
}

impl Cursor<'_> {
    fn peek(&self) -> Option<u8> {
        self.text.get(self.at).copied()
    }

    /// cJSON `buffer_skip_whitespace`: every byte up to and including 0x20.
    fn skip_ws(&mut self) {
        while self.peek().is_some_and(|b| b <= 32) {
            self.at += 1;
        }
    }

    fn eat(&mut self, byte: u8) -> bool {
        let hit = self.peek() == Some(byte);
        if hit {
            self.at += 1;
        }
        hit
    }

    /// cJSON `parse_string`: at an opening quote, decode up to the closing one into `out` (cut at its length; `None` for too long). The
    /// decoded length is returned either way so a caller comparing against a key can tell a longer string from a prefix.
    fn string(&mut self, out: &mut [u8]) -> Result<usize, ProfileJsonError> {
        if !self.eat(b'"') {
            return Err(ProfileJsonError::Malformed);
        }
        let mut len = 0;
        loop {
            let b = self.peek().ok_or(ProfileJsonError::Malformed)?;
            self.at += 1;
            let decoded = match b {
                b'"' => return Ok(len),
                b'\\' => {
                    let e = self.peek().ok_or(ProfileJsonError::Malformed)?;
                    self.at += 1;
                    match e {
                        b'b' => 0x08,
                        b'f' => 0x0c,
                        b'n' => b'\n',
                        b'r' => b'\r',
                        b't' => b'\t',
                        b'"' | b'\\' | b'/' => e,
                        _ => return Err(ProfileJsonError::Malformed),
                    }
                }
                other => other,
            };
            if let Some(dst) = out.get_mut(len) {
                *dst = decoded;
            }
            len += 1;
        }
    }

    /// cJSON `parse_number`: the longest `strtod` prefix of the run of number characters, as an `f64`.
    fn number(&mut self) -> Result<f64, ProfileJsonError> {
        let rest = &self.text[self.at..];
        let run = rest
            .iter()
            .take_while(|b| matches!(b, b'0'..=b'9' | b'+' | b'-' | b'e' | b'E' | b'.'))
            .count();
        let used = strtod_prefix(&rest[..run]);
        if used == 0 {
            return Err(ProfileJsonError::Malformed);
        }
        let text = core::str::from_utf8(&rest[..used]).map_err(|_| ProfileJsonError::Malformed)?;
        let value = f64::from_str(text).map_err(|_| ProfileJsonError::Malformed)?;
        self.at += used;
        Ok(value)
    }
}

/// Length of the longest prefix of `s` that C `strtod` reads as a decimal number: `[+-] (digits [. digits*] | . digits) [(e|E) [+-] digits]`,
/// or 0 when there is none. (`inf`, `nan` and hex floats cannot occur: their letters are not in the run.)
fn strtod_prefix(s: &[u8]) -> usize {
    let digits = |from: usize| {
        s[from.min(s.len())..]
            .iter()
            .take_while(|b| b.is_ascii_digit())
            .count()
    };
    let mut i = usize::from(matches!(s.first(), Some(b'+' | b'-')));
    let int = digits(i);
    i += int;
    let mut frac = 0;
    if s.get(i) == Some(&b'.') {
        frac = digits(i + 1);
        if int > 0 || frac > 0 {
            i += 1 + frac;
        }
    }
    if int == 0 && frac == 0 {
        return 0;
    }
    if matches!(s.get(i), Some(b'e' | b'E')) {
        let mut j = i + 1;
        if matches!(s.get(j), Some(b'+' | b'-')) {
            j += 1;
        }
        let exp = digits(j);
        if exp > 0 {
            i = j + exp;
        }
    }
    i
}

/// C `integer()`: `valuedouble == valueint` (cJSON saturates the int) and `min <= valueint <= max`.
fn integer(value: f64, min: i32, max: i32) -> Option<i32> {
    let int = value as i32; // saturating, like cJSON's INT_MAX / INT_MIN clamp
    (value == f64::from(int) && (min..=max).contains(&int)).then_some(int)
}

/// Fixed key table: the bit each key sets in the "seen" mask.
fn key_bit(key: &[u8]) -> Option<u8> {
    match key {
        b"slot" => Some(KEY_SLOT),
        b"priority" => Some(KEY_PRIORITY),
        b"name" => Some(KEY_NAME),
        b"ssid" => Some(KEY_SSID),
        b"password" => Some(KEY_PASSWORD),
        _ => None,
    }
}

/// C `profile_parse_json`: parse `{"slot":N,"priority":P,"name":"..","ssid":"..","password":".."}`, see the module documentation for the
/// exact language.
///
/// # Errors
/// A [`ProfileJsonError`]; nothing is returned for a refused command (C zeroes the output profile).
pub fn profile_parse_json(json: &[u8]) -> Result<ParsedProfile, ProfileJsonError> {
    let text = c_str(json);
    if text.len() > MAX_LEN {
        return Err(ProfileJsonError::TooLong);
    }
    // Avoid cJSON's embedded-NUL truncation: no \u escape, and no backslash at the very end.
    let mut i = 0;
    while i < text.len() {
        if text[i] == b'\\' {
            if text.get(i + 1).is_none_or(|&n| n == b'u') {
                return Err(ProfileJsonError::EscapeNotAllowed);
            }
            i += 1;
        }
        i += 1;
    }
    let body = if text.len() >= 4 && text.starts_with(&[0xEF, 0xBB, 0xBF]) {
        &text[3..]
    } else {
        text
    };
    let mut cur = Cursor { text: body, at: 0 };
    cur.skip_ws();
    if !cur.eat(b'{') {
        return Err(ProfileJsonError::Malformed);
    }
    cur.skip_ws();
    let mut seen = 0u8;
    let (mut slot, mut priority) = (0, 0);
    let mut profile = LegacyProfile::EMPTY;
    if cur.peek() != Some(b'}') {
        loop {
            cur.skip_ws();
            let mut key = [0u8; 8];
            let key_len = cur.string(&mut key)?;
            let bit = key
                .get(..key_len)
                .and_then(key_bit)
                .ok_or(ProfileJsonError::BadKey)?;
            if seen & bit != 0 {
                return Err(ProfileJsonError::BadKey);
            }
            seen |= bit;
            cur.skip_ws();
            if !cur.eat(b':') {
                return Err(ProfileJsonError::Malformed);
            }
            cur.skip_ws();
            match bit {
                KEY_SLOT | KEY_PRIORITY => {
                    if !matches!(cur.peek(), Some(b'-' | b'0'..=b'9')) {
                        return Err(ProfileJsonError::Malformed);
                    }
                    let value = cur.number()?;
                    if bit == KEY_SLOT {
                        slot = integer(value, 1, 8).ok_or(ProfileJsonError::BadValue)?;
                    } else {
                        priority = integer(value, 0, 100).ok_or(ProfileJsonError::BadValue)?;
                    }
                }
                _ => {
                    let field: &mut [u8] = match bit {
                        KEY_NAME => &mut profile.name,
                        KEY_SSID => &mut profile.ssid,
                        _ => &mut profile.pass,
                    };
                    let len = cur.string(field)?;
                    if len >= field.len() {
                        return Err(ProfileJsonError::BadValue);
                    }
                }
            }
            cur.skip_ws();
            if !cur.eat(b',') {
                break;
            }
        }
    }
    if !cur.eat(b'}') {
        return Err(ProfileJsonError::Malformed);
    }
    cur.skip_ws();
    if cur.peek().is_some() {
        return Err(ProfileJsonError::Malformed);
    }
    if seen != ALL_KEYS {
        return Err(ProfileJsonError::MissingKey);
    }
    profile.priority = priority as u8;
    if !profile.valid() {
        return Err(ProfileJsonError::InvalidProfile);
    }
    Ok(ParsedProfile {
        slot: slot as usize - 1,
        profile,
    })
}
