//! Pixel- and byte-exact comparison with the REAL C (tests/golden/*, generated by tools/gen_golden.py).

use std::collections::HashMap;
use std::fmt::Write as _;
use tdongle_lcd::panel::{self, Bringup, cmd};
use tdongle_lcd::{LcdState, View, backlight_duty, compose, format_count, format_duration, format_mbps, format_megabytes, render_row};

const SCENARIOS: &str = include_str!("golden/scenarios.txt");
const EXPECTED: &str = include_str!("golden/expected.txt");
const FRAMES: &[u8] = include_bytes!("golden/frames.bin");
const PANEL: &str = include_str!("golden/panel.txt");

fn unhex(s: &str) -> Vec<u8> {
    (0..s.len() / 2).map(|i| u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap()).collect()
}
fn hex(b: &[u8]) -> String {
    b.iter().fold(String::new(), |mut s, x| {
        write!(s, "{x:02x}").unwrap();
        s
    })
}
fn copy_into<const N: usize>(dst: &mut [u8; N], v: &str) {
    let b = unhex(v);
    assert!(b.len() <= N);
    dst[..b.len()].copy_from_slice(&b);
}

fn parse_state(fields: &[(&str, &str)]) -> (LcdState, String) {
    let mut s = LcdState::ZERO;
    let mut ver = String::from("0.3.0");
    for &(k, v) in fields {
        let n = || v.parse::<u64>().unwrap();
        let b = || v != "0";
        match k {
            "ver" => ver = String::from_utf8(unhex(v)).unwrap(),
            "full" => {}
            "bridge" => s.bridge = b(),
            "wifi" => s.wifi = b(),
            "saved_wifi" => s.saved_wifi = b(),
            "recovery" => s.recovery = b(),
            "starting" => s.starting = b(),
            "installing" => s.installing = b(),
            "usb" => s.usb = b(),
            "usb_configured" => s.usb_configured = b(),
            "usb_suspended" => s.usb_suspended = b(),
            "saved" => s.saved = n() as u32,
            "enabled" => s.enabled = n() as u32,
            "ready" => s.ready = n() as u32,
            "login" => s.login = n() as u32,
            "failed" => s.failed = n() as u32,
            "page" => s.page = n() as u32,
            "rssi_valid" => s.rssi_valid = b(),
            "rssi" => s.rssi = v.parse().unwrap(),
            "ssid" => copy_into(&mut s.ssid, v),
            "setup" => s.setup = b(),
            "ap_ssid" => copy_into(&mut s.ap_ssid, v),
            "setup_seconds_left" => s.setup_seconds_left = n() as u32,
            "down_kbps" => s.down_kbps = n() as u32,
            "up_kbps" => s.up_kbps = n() as u32,
            "down_bytes" => s.down_bytes = n(),
            "up_bytes" => s.up_bytes = n(),
            "down_frames" => s.down_frames = n(),
            "up_frames" => s.up_frames = n(),
            "bars" => copy_into(&mut s.bars, v),
            "uptime_s" => s.uptime_s = n() as u32,
            "wifi_up_s" => s.wifi_up_s = n() as u32,
            "connects" => s.connects = n() as u32,
            "last_reason" => s.last_reason = n() as u32,
            "usb_resets" => s.usb_resets = n() as u32,
            "heap_free" => s.heap_free = n() as u32,
            "heap_min" => s.heap_min = n() as u32,
            "heap_largest" => s.heap_largest = n() as u32,
            "reset_reason" => s.reset_reason = n() as u32,
            "boots" => s.boots = n() as u32,
            "watchdogs" => s.watchdogs = n() as u32,
            "panics" => s.panics = n() as u32,
            "health_view" => s.health_view = n() as u32,
            "active_slot" => s.active_slot = n() as u32,
            "active_name" => copy_into(&mut s.active_name, v),
            other => panic!("unknown key {other}"),
        }
    }
    (s, ver)
}

fn crc32(rows: impl Iterator<Item = [u16; 160]>) -> u32 {
    let mut crc = 0xFFFF_FFFFu32;
    for row in rows {
        for p in row {
            for byte in p.to_le_bytes() {
                crc ^= u32::from(byte);
                for _ in 0..8 {
                    crc = (crc >> 1) ^ (0xEDB8_8320 & (crc & 1).wrapping_neg());
                }
            }
        }
    }
    !crc
}
fn pixel_crc(v: &View) -> u32 {
    crc32((0..83).map(|k| {
        let y = if k < 82 { k } else { 255 };
        let mut row = [0u16; 160];
        render_row(v, y, &mut row);
        row
    }))
}
fn decode_frame(data: &[u8]) -> Vec<[u16; 160]> {
    let mut pos = 0;
    let mut rows = Vec::new();
    for _ in 0..80 {
        let n = data[pos];
        pos += 1;
        let mut row = Vec::new();
        for _ in 0..n {
            let v = u16::from(data[pos]) | u16::from(data[pos + 1]) << 8;
            row.extend(std::iter::repeat_n(v, usize::from(data[pos + 2])));
            pos += 3;
        }
        rows.push(<[u16; 160]>::try_from(row).unwrap());
    }
    assert_eq!(pos, data.len());
    rows
}

fn kv(line: &str) -> (&str, HashMap<&str, &str>) {
    let mut it = line.split(' ');
    let name = it.next().unwrap();
    (name, it.filter_map(|t| t.split_once('=')).collect())
}

#[test]
fn every_scenario_matches_the_c() {
    let expected: HashMap<&str, HashMap<&str, &str>> = EXPECTED.lines().filter(|l| !l.starts_with('#')).map(kv).collect();
    let (mut views, mut frames, mut formats, mut duties) = (0, 0, 0, 0);
    for line in SCENARIOS.lines().filter(|l| !l.starts_with('#') && !l.is_empty()) {
        let mut tok = line.split(' ');
        let kind = tok.next().unwrap();
        let name = tok.next().unwrap();
        let rest: Vec<&str> = tok.collect();
        let want = &expected[name];
        let fields: Vec<(&str, &str)> = rest.iter().filter_map(|t| t.split_once('=')).collect();
        let view: Option<View> = match kind {
            "S" => {
                let (s, ver) = parse_state(&fields);
                // The C poisons the view before compose (0x5a): compose must overwrite every byte.
                let mut v = View { text: [0x5a; 135], bars: [0x5a; 32], attention: true, layout: 0x5a, bar_count: 0x5a };
                tdongle_lcd::view::compose_into(&s, &ver, &mut v);
                assert_eq!(v, compose(&s, &ver), "{name}: compose_into over a dirty view");
                Some(v)
            }
            "R" => {
                let f: HashMap<_, _> = fields.iter().copied().collect();
                let raw = unhex(f["rows"]);
                let mut rows = [[0u8; 27]; 5];
                for (i, r) in rows.iter_mut().enumerate() {
                    r.copy_from_slice(&raw[i * 27..(i + 1) * 27]);
                }
                let mut v = View { text: [0x5a; 135], bars: [0x5a; 32], attention: false, layout: 0x5a, bar_count: 0x5a };
                tdongle_lcd::view::compose_rows_into(&mut v, &rows, f["attention"] == "1");
                Some(v)
            }
            "V" => {
                let f: HashMap<_, _> = fields.iter().copied().collect();
                let mut v = View::ZERO;
                v.text.copy_from_slice(&unhex(f["text"]));
                v.bars.copy_from_slice(&unhex(f["bars"]));
                v.attention = f["attention"] == "1";
                v.layout = f["layout"].parse().unwrap();
                v.bar_count = f["bar_count"].parse().unwrap();
                Some(v)
            }
            "F" => {
                let (k, size, val) = (rest[0], rest[1].parse::<usize>().unwrap(), rest[2].parse::<u64>().unwrap());
                let mut buf = [0u8; 64];
                let out = &mut buf[..size];
                match k {
                    "dur" => format_duration(out, val as u32),
                    "cnt" => format_count(out, val),
                    "mbps" => format_mbps(out, val as u32),
                    _ => format_megabytes(out, val),
                }
                let n = buf.iter().position(|&c| c == 0).unwrap();
                assert!(n < size.max(1), "{name}: NUL inside the buffer");
                assert_eq!(hex(&buf[..n]), want["out"], "{name} ({k} size {size} value {val})");
                formats += 1;
                None
            }
            "D" => {
                let p: u32 = rest[0].parse().unwrap();
                assert_eq!(backlight_duty(p).to_string(), want["duty"], "{name}");
                duties += 1;
                None
            }
            "G" => {
                let mut got = String::new();
                for c in 0..=255u8 {
                    for r in 0..7 {
                        write!(got, "{:02x}", tdongle_lcd::font::glyph(c, r)).unwrap();
                    }
                }
                assert_eq!(got, want["glyphs"]);
                None
            }
            other => panic!("kind {other}"),
        };
        let Some(v) = view else { continue };
        assert_eq!(hex(&view_bytes(&v)), want["view"], "{name}: view bytes (memcmp identity with the C struct)");
        assert_eq!(format!("{:08x}", pixel_crc(&v)), want["crc"], "{name}: pixel CRC");
        views += 1;
        if let Some(f) = want.get("frame") {
            let (off, len) = f.split_once(':').unwrap();
            let (off, len): (usize, usize) = (off.parse().unwrap(), len.parse().unwrap());
            let rows = decode_frame(&FRAMES[off..off + len]);
            for (y, want_row) in rows.iter().enumerate() {
                let mut row = [0u16; 160];
                render_row(&v, y, &mut row);
                assert_eq!(&row, want_row, "{name}: row {y}");
            }
            frames += 1;
        }
    }
    assert!(views > 3000 && frames > 120 && formats > 500 && duties > 100, "{views} {frames} {formats} {duties}");
}

/// The 170 bytes of the C `lcd_view` (union text, bars, attention, layout, bar_count).
fn view_bytes(v: &View) -> Vec<u8> {
    let mut b = Vec::with_capacity(170);
    b.extend_from_slice(&v.text);
    b.extend_from_slice(&v.bars);
    b.push(u8::from(v.attention));
    b.push(v.layout);
    b.push(v.bar_count);
    b
}

#[test]
fn view_equality_is_memcmp() {
    let s = LcdState::ZERO;
    assert_eq!(compose(&s, "1"), compose(&s, "1"));
    assert_ne!(compose(&s, "1"), compose(&s, "2"));
    assert_ne!(compose(&s, "1"), View::POISONED);
    assert_eq!(core::mem::size_of::<View>(), 170);
    // A shorter field written over a longer one keeps the old tail in the C (snprintf writes only the NUL); compose zeroes first so two
    // composes of equal states agree whatever the previous view held.
    let mut dirty = compose(&LcdState { wifi: true, bridge: true, ..LcdState::ZERO }, "9.9.9");
    tdongle_lcd::view::compose_into(&s, "1", &mut dirty);
    assert_eq!(dirty, compose(&s, "1"));
}

// ---- panel -------------------------------------------------------------------------------------------------------------------------

fn trace_cmd(out: &mut String, c: &panel::Cmd) {
    write!(out, "CMD {:02x}", c.cmd).unwrap();
    for b in c.data() {
        write!(out, " {b:02x}").unwrap();
    }
    out.push('\n');
    writeln!(out, "DELAY {}", c.delay_ms).unwrap();
}

/// What the real driver does at start (the C `esp_lcd_panel_*` chain of lcd.c): reset pulse, then every command.
fn rust_start(out: &mut String) {
    writeln!(out, "GPIO_OUT mask={:x}", 1u64 << panel::PIN_RST).unwrap();
    writeln!(out, "GPIO {} 0\nDELAY {}\nGPIO {} 1\nDELAY {}", panel::PIN_RST, panel::RESET_LOW_MS, panel::PIN_RST, panel::RESET_HIGH_MS).unwrap();
    for (i, c) in Bringup::new().enumerate() {
        let n = panel::BRINGUP_LEN;
        assert!(i < n);
        // The C sends the first SLPOUT and delay, MADCTL and COLMOD without a delay line for the last four configuration calls.
        let configuration = i >= 3 + panel::INIT_SEQUENCE.len();
        if configuration {
            write!(out, "CMD {:02x}", c.cmd).unwrap();
            for b in c.data() {
                write!(out, " {b:02x}").unwrap();
            }
            out.push('\n');
        } else if i < 3 {
            write!(out, "CMD {:02x}", c.cmd).unwrap();
            for b in c.data() {
                write!(out, " {b:02x}").unwrap();
            }
            out.push('\n');
            if c.delay_ms != 0 {
                writeln!(out, "DELAY {}", c.delay_ms).unwrap();
            }
        } else {
            trace_cmd(out, &c);
        }
    }
    assert_eq!(Bringup::new().count(), panel::BRINGUP_LEN);
}

fn rust_draw(out: &mut String, x0: u16, y0: u16, x1: u16, y1: u16) {
    let (c, r) = panel::window(x0, y0, x1, y1);
    writeln!(out, "CMD 2a {}", c.iter().map(|b| format!("{b:02x}")).collect::<Vec<_>>().join(" ")).unwrap();
    writeln!(out, "CMD 2b {}", r.iter().map(|b| format!("{b:02x}")).collect::<Vec<_>>().join(" ")).unwrap();
    writeln!(out, "COLOR 2c {}", usize::from(x1 - x0) * usize::from(y1 - y0) * 2).unwrap();
}

#[test]
fn panel_wire_trace_matches_the_real_st7735_driver() {
    let mut got = String::new();
    for rotation in 0..2u8 {
        writeln!(got, "## start rotation {rotation}").unwrap();
        rust_start(&mut got);
        if rotation == 1 {
            writeln!(got, "## apply rotation 1").unwrap();
            let c = panel::rotation_cmd(1).unwrap();
            writeln!(got, "CMD 36 {:02x}", c.data()[0]).unwrap();
        }
        let mut y = 0u16;
        while y < 80 {
            writeln!(got, "## draw row {y}").unwrap();
            rust_draw(&mut got, 0, y, 160, y + 1);
            y += if !(3..=76).contains(&y) { 1 } else { 37 };
        }
        writeln!(got, "## draw window 5 7 100 20").unwrap();
        rust_draw(&mut got, 5, 7, 100, 20);
        writeln!(got, "## draw window 0 0 300 280").unwrap();
        rust_draw(&mut got, 0, 0, 300, 280);
        if rotation == 1 {
            writeln!(got, "## apply rotation 0").unwrap();
            let c = panel::rotation_cmd(0).unwrap();
            writeln!(got, "CMD 36 {:02x}", c.data()[0]).unwrap();
        }
    }
    assert_eq!(got, PANEL);
}

#[test]
fn panel_constants_and_wire_bytes() {
    assert_eq!((panel::PIN_MOSI, panel::PIN_CLK, panel::PIN_CS, panel::PIN_DC, panel::PIN_RST, panel::PIN_BL), (3, 5, 4, 2, 1, 38));
    assert_eq!((panel::WIDTH, panel::HEIGHT, panel::GAP_X, panel::GAP_Y, panel::SPI_HZ), (160, 80, 1, 26, 20_000_000));
    assert_eq!(panel::madctl(0), 0xa8);
    assert_eq!(panel::madctl(1), 0x68);
    assert_eq!(panel::madctl(7), 0xa8);
    assert!(panel::rotation_cmd(2).is_none());
    assert_eq!(panel::INIT_SEQUENCE[0].cmd, cmd::SWRESET);
    assert_eq!(panel::row_window(0), ([0, 1, 0, 160], [0, 26, 0, 26]));
    assert_eq!(panel::row_window(79), ([0, 1, 0, 160], [0, 105, 0, 105]));
    // lcd.c: `pixels[x] = (pixels[x] << 8) | (pixels[x] >> 8)` then the SPI sends the u16s from memory (little endian CPU).
    let mut row = [0u16; 160];
    for (i, p) in row.iter_mut().enumerate() {
        *p = (i as u16).wrapping_mul(0x0407).wrapping_add(0x1234);
    }
    let wire = panel::to_wire(&row);
    let mut swapped = row;
    panel::swap_row(&mut swapped);
    let mut le = Vec::new();
    for p in swapped {
        le.extend_from_slice(&p.to_le_bytes());
    }
    assert_eq!(wire.as_slice(), le.as_slice());
    assert_eq!(wire[0], (row[0] >> 8) as u8);
}
