#!/usr/bin/env python3
"""Extract the RFC 8439 test vectors used by test_wg_crypto.c.

Usage: gen_wg_crypto_rfc8439_vectors.py rfc8439.txt > wg_crypto_rfc8439_vectors.h

The header is checked in; this script exists so the vectors are traceable to the
RFC text (https://www.rfc-editor.org/rfc/rfc8439.txt) rather than hand-typed.
"""
import re
import sys

lines = open(sys.argv[1]).read().split('\n')
dump = re.compile(r'^\s+(\d{3})\s+((?:[0-9a-f]{2} )*[0-9a-f]{2})(?:\s{2,}.*)?$')


def section(start, end):
    s = next(i for i, l in enumerate(lines) if l.startswith(start))
    e = next(i for i, l in enumerate(lines) if i > s and l.startswith(end))
    return lines[s:e]


def blocks(sec):
    """Return [(label, bytes)] for every offset-dump block in order."""
    out, i = [], 0
    while i < len(sec):
        m = dump.match(sec[i])
        if m and int(m.group(1)) == 0:
            j = i - 1
            while not sec[j].strip():
                j -= 1
            label = sec[j].strip().rstrip(':')
            data = b''
            while i < len(sec) and dump.match(sec[i]):
                data += bytes(int(x, 16) for x in dump.match(sec[i]).group(2).split())
                i += 1
            out.append((label, data))
        else:
            i += 1
    return out


def counters(sec, pat):
    return [int(m.group(1)) for l in sec for m in [re.search(pat, l)] if m]


def arr(name, b):
    body = ', '.join('0x%02x' % x for x in b) if b else '0'
    return 'static const uint8_t %s[%d] = {%s};' % (name, max(len(b), 1), body)


out = []
emit = out.append
emit('/* Generated by gen_wg_crypto_rfc8439_vectors.py from RFC 8439 -- do not edit. */')
emit('#ifndef WG_CRYPTO_RFC8439_VECTORS_H\n#define WG_CRYPTO_RFC8439_VECTORS_H\n#include <stdint.h>\n#include <stddef.h>\n')
emit('struct v_block { const uint8_t *key, *nonce12, *keystream; uint32_t counter; };')
emit('struct v_enc { const uint8_t *key, *nonce12, *pt, *ct; uint32_t counter; size_t len; };')
emit('struct v_poly { const uint8_t *key, *msg, *tag; size_t len; };')
emit('struct v_polykey { const uint8_t *key, *nonce12, *otk; };')
emit('struct v_aead { const uint8_t *key, *nonce12, *aad, *pt, *ct, *tag; size_t aad_len, len; };\n')

# A.1 block function
sec = section('A.1.  The ChaCha20 Block', 'A.2.')
bl = blocks(sec)
ctr = counters(sec, r'Block Counter = (\d+)')
rows = []
for n in range(len(ctr)):
    k, no, ks = bl[3 * n][1], bl[3 * n + 1][1], bl[3 * n + 2][1]
    emit(arr('a1_%d_key' % n, k)); emit(arr('a1_%d_nonce' % n, no)); emit(arr('a1_%d_ks' % n, ks))
    rows.append('{a1_%d_key, a1_%d_nonce, a1_%d_ks, %d}' % (n, n, n, ctr[n]))
emit('static const struct v_block rfc_a1[] = {%s};' % ',\n    '.join(rows))

# A.2 encryption
sec = section('A.2.  ChaCha20 Encryption', 'A.3.')
bl = blocks(sec)
ctr = counters(sec, r'Initial Block Counter = (\d+)')
rows = []
for n in range(len(ctr)):
    k, no, pt, ct = [bl[5 * 0 + 4 * n + i][1] for i in range(4)]
    assert len(pt) == len(ct)
    for nm, v in (('key', k), ('nonce', no), ('pt', pt), ('ct', ct)):
        emit(arr('a2_%d_%s' % (n, nm), v))
    rows.append('{a2_%d_key, a2_%d_nonce, a2_%d_pt, a2_%d_ct, %d, %d}' % (n, n, n, n, ctr[n], len(pt)))
emit('static const struct v_enc rfc_a2[] = {%s};' % ',\n    '.join(rows))

# Poly1305: 2.5.2, A.3 #1-#4 (dumps) and #5-#11 (R/S/data/tag)
sec = section('A.3.  Poly1305 Message', 'A.4.')
bl = blocks(sec)
polys = []
for n in range(4):
    polys.append((bl[3 * n][1], bl[3 * n + 1][1], bl[3 * n + 2][1]))
txt = '\n'.join(sec)
for m in re.finditer(r'Test Vector #(\d+): .*?\n\s+R:\n(.*?)\n\s+S:\n(.*?)\n\s+data:\n(.*?)\n\s+tag:\n(.*?)\n', txt, re.S):
    if int(m.group(1)) < 5:
        continue
    h = lambda s: bytes(int(x, 16) for x in s.split())
    polys.append((h(m.group(2)) + h(m.group(3)), h(m.group(4)), h(m.group(5))))
assert len(polys) == 11
sec252 = section('2.5.2.  Poly1305 Example', '2.6.')
key252 = bytes(int(x, 16) for x in '85:d6:be:78:57:55:6d:33:7f:44:52:fe:42:d5:06:a8:01:03:80:8a:fb:0d:b2:fd:4a:bf:f6:af:41:49:f5:1b'.split(':'))
msg252 = blocks(sec252)[0][1]
tag252 = bytes(int(x, 16) for x in re.search(r'Tag:\s*\n?\s*([0-9a-f:]{47})', '\n'.join(sec252)).group(1).split(':'))
polys.append((key252, msg252, tag252))
rows = []
for n, (k, m_, t) in enumerate(polys):
    emit(arr('p_%d_key' % n, k)); emit(arr('p_%d_msg' % n, m_)); emit(arr('p_%d_tag' % n, t))
    rows.append('{p_%d_key, p_%d_msg, p_%d_tag, %d}' % (n, n, n, len(m_)))
emit('static const struct v_poly rfc_poly[] = {%s};' % ',\n    '.join(rows))

# A.4 poly key generation
sec = section('A.4.  Poly1305 Key Generation', 'A.5.')
bl = blocks(sec)
rows = []
for n in range(3):
    k, no, o = bl[3 * n][1], bl[3 * n + 1][1], bl[3 * n + 2][1]
    emit(arr('a4_%d_key' % n, k)); emit(arr('a4_%d_nonce' % n, no)); emit(arr('a4_%d_otk' % n, o))
    rows.append('{a4_%d_key, a4_%d_nonce, a4_%d_otk}' % (n, n, n))
emit('static const struct v_polykey rfc_a4[] = {%s};' % ',\n    '.join(rows))

# AEAD: 2.8.2 (nonce prefix 07 00 00 00 -> not expressible with the WireGuard 64-bit nonce API)
# and A.5 (nonce prefix 0 -> expressible).
sec = section('2.8.2.  Example', '3.  Implementation Advice')
bl = dict()
for label, data in blocks(sec):
    bl.setdefault(label, data)
iv = bl['IV']; fixed = bl['32-bit fixed-common part']
tag282 = bytes(int(x, 16) for x in re.search(r'Tag:\s*\n\s*([0-9a-f:]{47})', '\n'.join(sec)).group(1).split(':'))
# The ciphertext printed in the RFC is 114 bytes (no tag).
b282 = blocks(sec)
aad282 = b282[1][1]
assert b282[0][0].startswith('Plaintext') and b282[1][0].startswith('AAD')
emit(arr('e282_key', bl['Key'])); emit(arr('e282_nonce', fixed + iv)); emit(arr('e282_aad', aad282))
emit(arr('e282_pt', b282[0][1])); emit(arr('e282_ct', bl['Ciphertext'])); emit(arr('e282_tag', tag282))
sec = section('A.5.  ChaCha20-Poly1305 AEAD', 'Appendix B.')
b5 = {l: d for l, d in blocks(sec)}
b5k = blocks(sec)
key5 = b5k[0][1]
emit(arr('e5_key', key5)); emit(arr('e5_ct', b5['Ciphertext'])); emit(arr('e5_nonce', b5['The nonce']))
emit(arr('e5_aad', b5['The AAD'])); emit(arr('e5_tag', b5['Received Tag'])); emit(arr('e5_pt', b5['Plaintext']))
emit('static const struct v_aead rfc_aead[] = {')
emit('  {e282_key, e282_nonce, e282_aad, e282_pt, e282_ct, e282_tag, sizeof e282_aad, sizeof e282_pt},')
emit('  {e5_key, e5_nonce, e5_aad, e5_pt, e5_ct, e5_tag, sizeof e5_aad, sizeof e5_pt},')
emit('};')
emit('\n#endif')
print('\n'.join(out))
