//! The DHCP server of the setup access point (ADR 0024 of the C firmware), as pure `no_std` logic.
//!
//! This is a behaviour-matched port of ESP-IDF v5.5.5 `components/lwip/apps/dhcpserver/dhcpserver.c` (the server `esp_netif` starts on
//! the soft-AP interface) with the configuration the C firmware's `setup_ap.inc` gives it and the IDF defaults of
//! `CONFIG_LWIP_DHCPS_LEASE_UNIT=60`, `CONFIG_LWIP_DHCPS_MAX_STATION_NUM=8`, `CONFIG_LWIP_DHCPS_STATIC_ENTRIES=y`,
//! `CONFIG_LWIP_DHCPS_ADD_DNS=y`: address 192.168.4.1/24, pool 192.168.4.2 to 192.168.4.101, lease 120 units of 60 s (two hours), router
//! option (the AP's gateway, 192.168.4.1), DNS option 192.168.4.1 (the captive DNS), no captive-portal option 114.
//!
//! The firmware owns the UDP socket (port 67, bound to the AP interface). For each datagram it calls [`Server::handle`] with the payload
//! and a millisecond clock and sends the returned bytes to port 68 of [`Reply::dest`]. With a [`Dest::Unicast`] the firmware has to be able
//! to reach a client that does not have the address yet (lwIP adds a temporary static ARP entry for `ip` -> `mac`, then removes it).
//!
//! No allocation, no unsafe; every length is checked, so any bytes are safe input. See the crate tests for the semantics ported from lwIP
//! and `tests/golden.txt` for replies generated by the real `dhcpserver.c`.

#![no_std]
#![forbid(unsafe_code)]
#![deny(missing_docs)]

/// A request longer than this is dropped (lwIP: `p->tot_len > 1500`).
pub const MAX_REQUEST: usize = 1500;
/// The shortest request that can hold the fixed BOOTP header and the magic cookie.
pub const MIN_REQUEST: usize = 240;
/// lwIP always sends at least `sizeof(struct dhcps_msg)` bytes (236 + 312). `out` must hold [`reply_len`] bytes.
pub const MIN_REPLY: usize = 548;
/// Lease table size: the station limit (8) plus the one entry that exists between an allocation and the eviction of the oldest.
pub const CAPACITY: usize = 9;
/// lwIP `DHCPS_MAX_LEASE`: the default pool never holds more addresses than this.
pub const MAX_POOL: u32 = 0x64;

const MAGIC: [u8; 4] = [0x63, 0x82, 0x53, 0x63];
const OPT_PAD: u8 = 0;
const OPT_END: u8 = 255;
const OPT_REQ_IP: u8 = 50;
const OPT_MSG_TYPE: u8 = 53;

const DISCOVER: u8 = 1;
const REQUEST: u8 = 3;
const DECLINE: u8 = 4;
const RELEASE: u8 = 7;
const INFORM: u8 = 8;

/// Where a reply goes. The port is always 68.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Dest {
    /// 255.255.255.255.
    Broadcast,
    /// The address from `giaddr`, `ciaddr` or `yiaddr` (lwIP's order). `mac` is the client hardware address: lwIP installs a temporary
    /// static ARP entry `ip` -> `mac` for the send, so the firmware has to do the equivalent (or send as an Ethernet frame to `mac`).
    Unicast {
        /// IPv4 destination.
        ip: [u8; 4],
        /// Client hardware address (`chaddr[0..6]`).
        mac: [u8; 6],
    },
}

/// What kind of message the reply is.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ReplyKind {
    /// DHCPOFFER.
    Offer,
    /// DHCPACK for a REQUEST; the client now holds `yiaddr` (lwIP calls the `IP_EVENT_AP_STAIPASSIGNED` callback for it).
    Ack,
    /// DHCPNAK.
    Nak,
    /// DHCPACK for an INFORM (no `yiaddr`, no lease time).
    InformAck,
}

/// A reply to send: `out[..len]` to `dest`:68.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Reply {
    /// Bytes of `out` that make the datagram.
    pub len: usize,
    /// Destination.
    pub dest: Dest,
    /// Message type.
    pub kind: ReplyKind,
    /// `yiaddr` of the reply (all zero for NAK and INFORM).
    pub yiaddr: [u8; 4],
    /// Client hardware address.
    pub mac: [u8; 6],
}

/// Why a [`Config`] is rejected (lwIP: `dhcps_start` returns `ERR_ARG`).
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ConfigError {
    /// The netmask is not a contiguous run of one bits.
    BadNetmask,
    /// The server address is the network or the broadcast address of its subnet.
    BadServerIp,
    /// `lease_secs` is 0 or too long for the wrap-safe clock (more than [`Config::MAX_LEASE_SECS`]).
    BadLease,
    /// `max_stations` is 0 or more than `CAPACITY - 1`.
    BadStations,
}

/// Server configuration.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Config {
    /// The server's (the access point's) address; also the DHCP server identifier.
    pub server_ip: [u8; 4],
    /// Subnet mask.
    pub netmask: [u8; 4],
    /// Explicit pool `(first, last)`; like lwIP it is ignored for the default pool when it holds the server, is outside the subnet or
    /// has more than [`MAX_POOL`] addresses. `None`: the default pool, the larger side of the subnet next to the server, at most 100.
    pub pool: Option<([u8; 4], [u8; 4])>,
    /// Lease time in seconds (option 51; lwIP: `DHCPS_LEASE_TIME_DEF` 120 units x 60 s).
    pub lease_secs: u32,
    /// Leases kept before the oldest is evicted (`CONFIG_LWIP_DHCPS_MAX_STATION_NUM`).
    pub max_stations: usize,
    /// Option 3 (router); lwIP sends the netif gateway when non-zero.
    pub router: Option<[u8; 4]>,
    /// Option 6, first DNS server.
    pub dns: [u8; 4],
    /// Option 6, second DNS server (lwIP `DNS_TYPE_BACKUP`; zero is "none").
    pub dns_backup: Option<[u8; 4]>,
}

impl Config {
    /// Longest lease the millisecond clock can order (a quarter of the 32-bit range, about 12 days).
    pub const MAX_LEASE_SECS: u32 = 1_000_000;

    /// What the C firmware's setup access point runs: 192.168.4.1/24, DNS 192.168.4.1, gateway 192.168.4.1, lease two hours.
    pub const fn setup_ap() -> Config {
        Config {
            server_ip: [192, 168, 4, 1],
            netmask: [255, 255, 255, 0],
            pool: None,
            lease_secs: 120 * 60,
            max_stations: 8,
            router: Some([192, 168, 4, 1]),
            dns: [192, 168, 4, 1],
            dns_backup: None,
        }
    }
}

#[derive(Clone, Copy, Debug)]
struct Lease {
    ip: u32,
    mac: [u8; 6],
    expires: u32,
}

/// One lease, as reported by [`Server::leases`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct LeaseInfo {
    /// Leased address.
    pub ip: [u8; 4],
    /// Client hardware address.
    pub mac: [u8; 6],
}

/// The DHCP server: configuration plus the lease table (`CAPACITY` entries, ordered by address like lwIP's list).
#[derive(Clone, Debug)]
pub struct Server {
    cfg: Config,
    server: u32,
    mask: u32,
    pool_start: u32,
    pool_end: u32,
    lease_ms: u32,
    leases: [Lease; CAPACITY],
    n: usize,
    /// lwIP `client_address_plus`: where the next fresh allocation starts.
    plus: u32,
    /// lwIP `has_declined_ip`.
    declined: bool,
}

fn be(a: [u8; 4]) -> u32 {
    u32::from_be_bytes(a)
}

fn state_cmp_net(a: u32, b: u32, mask: u32) -> bool {
    a & mask == b & mask
}

/// Bytes of the reply for a request of `request_len` bytes: `max(548, request_len)`.
pub const fn reply_len(request_len: usize) -> usize {
    if request_len > MIN_REPLY { request_len } else { MIN_REPLY }
}

/// Walks the options of lwIP's `parse_options`/`dhcps_get_option_msg_type`: pad skipped, end stops, an option that does not fit stops.
struct Options<'a> {
    rest: &'a [u8],
}

impl<'a> Iterator for Options<'a> {
    type Item = (u8, &'a [u8]);
    fn next(&mut self) -> Option<Self::Item> {
        loop {
            let code = *self.rest.first()?;
            if code == OPT_PAD {
                self.rest = &self.rest[1..];
                continue;
            }
            if code == OPT_END {
                self.rest = &[];
                return None;
            }
            let len = usize::from(*self.rest.get(1)?);
            let Some(data) = self.rest.get(2..2 + len) else {
                self.rest = &[];
                return None;
            };
            self.rest = &self.rest[2 + len..];
            return Some((code, data));
        }
    }
}

struct Writer<'a> {
    buf: &'a mut [u8],
    pos: usize,
}

impl Writer<'_> {
    fn put(&mut self, bytes: &[u8]) -> Option<()> {
        let end = self.pos.checked_add(bytes.len())?;
        self.buf.get_mut(self.pos..end)?.copy_from_slice(bytes);
        self.pos = end;
        Some(())
    }
    fn opt(&mut self, code: u8, data: &[u8]) -> Option<()> {
        self.put(&[code, data.len() as u8])?;
        self.put(data)
    }
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum State {
    Offer,
    Ack,
    Nak,
    Idle,
    Release,
    Decline,
    InformAck,
}

impl Server {
    /// Builds the server (lwIP `dhcps_new` + `dhcps_start`): validates the configuration and computes the pool.
    pub fn new(cfg: Config) -> Result<Server, ConfigError> {
        let mask = be(cfg.netmask);
        if (mask.wrapping_sub(1) | mask) != 0xFFFF_FFFF {
            return Err(ConfigError::BadNetmask);
        }
        let server = be(cfg.server_ip);
        if server == server & mask || server == server | !mask {
            return Err(ConfigError::BadServerIp);
        }
        if cfg.lease_secs == 0 || cfg.lease_secs > Config::MAX_LEASE_SECS {
            return Err(ConfigError::BadLease);
        }
        if cfg.max_stations == 0 || cfg.max_stations >= CAPACITY {
            return Err(ConfigError::BadStations);
        }
        let (mut start, mut end, mut ok) = (0, 0, false);
        if let Some((s, e)) = cfg.pool {
            let (s, e) = (be(s), be(e));
            // dhcps_poll_set: not containing the server, inside the subnet, at most DHCPS_MAX_LEASE addresses.
            ok = !(server >= s && server <= e)
                && state_cmp_net(s, server, mask)
                && state_cmp_net(e, server, mask)
                && e.wrapping_sub(s).wrapping_add(1) <= MAX_POOL;
            (start, end) = (s, e);
        }
        if !ok {
            let net = server & mask;
            let bcast = net | !mask;
            if server - net > bcast - server {
                start = net + 1;
                end = server - 1;
            } else {
                start = server + 1;
                end = bcast - 1;
            }
            if end - start + 1 > MAX_POOL {
                end = start + MAX_POOL - 1;
            }
        }
        Ok(Server {
            cfg,
            server,
            mask,
            pool_start: start,
            pool_end: end,
            lease_ms: cfg.lease_secs * 1000,
            leases: [Lease { ip: 0, mac: [0; 6], expires: 0 }; CAPACITY],
            n: 0,
            plus: start,
            declined: false,
        })
    }

    /// First and last address of the pool.
    pub fn pool(&self) -> ([u8; 4], [u8; 4]) {
        (self.pool_start.to_be_bytes(), self.pool_end.to_be_bytes())
    }

    /// Number of live leases (as of the last [`Server::handle`] or [`Server::expire`]).
    pub fn lease_count(&self) -> usize {
        self.n
    }

    /// The `i`-th lease in address order.
    pub fn lease(&self, i: usize) -> Option<LeaseInfo> {
        let l = self.leases.get(..self.n)?.get(i)?;
        Some(LeaseInfo { ip: l.ip.to_be_bytes(), mac: l.mac })
    }

    /// The address leased to `mac` (lwIP `dhcp_search_ip_on_mac`).
    pub fn lease_of(&self, mac: [u8; 6]) -> Option<[u8; 4]> {
        self.leases[..self.n].iter().find(|l| l.mac == mac).map(|l| l.ip.to_be_bytes())
    }

    /// Drops leases whose time is up (lwIP's one-second timer; [`Server::handle`] calls it first). Call at least every few days of
    /// idle time: the wrap-safe comparison orders deadlines within half the 32-bit millisecond range (24 days).
    pub fn expire(&mut self, now_ms: u32) {
        let mut i = 0;
        while i < self.n {
            if (self.leases[i].expires.wrapping_sub(now_ms) as i32) <= 0 {
                self.remove(i);
            } else {
                i += 1;
            }
        }
    }

    fn remove(&mut self, i: usize) {
        self.leases.copy_within(i + 1..self.n, i);
        self.n -= 1;
    }

    fn insert(&mut self, l: Lease) -> usize {
        // node_insert_to_list: before the first lease with a greater address, else at the end.
        let mut at = 0;
        while at < self.n && l.ip >= self.leases[at].ip {
            at += 1;
        }
        self.leases.copy_within(at..self.n, at + 1);
        self.leases[at] = l;
        self.n += 1;
        at
    }

    /// kill_oldest_dhcps_pool: with more than `max_stations` leases the one closest to expiry goes (first in address order on a tie).
    fn evict_oldest(&mut self, now_ms: u32) {
        while self.n > self.cfg.max_stations {
            let mut min = 0;
            for i in 1..self.n {
                let r = self.leases[i].expires.wrapping_sub(now_ms) as i32;
                let m = self.leases[min].expires.wrapping_sub(now_ms) as i32;
                if r < m {
                    min = i;
                }
            }
            self.remove(min);
        }
    }

    /// Processes one datagram received on UDP port 67 at `now_ms` (any wrapping millisecond clock). Returns the reply to send, if any.
    ///
    /// `out` must hold [`reply_len`]`(request.len())` bytes (548 for every normal request, at most 1500), otherwise nothing is
    /// processed. Requests that are not BOOTREQUEST, are shorter than 240 bytes, longer than 1500, or lack the magic cookie are ignored.
    /// Like lwIP the reply is the request with the header fields rewritten and the options replaced, zero padded to 548 bytes, so
    /// bytes of the request's own options can trail the END option.
    pub fn handle(&mut self, request: &[u8], now_ms: u32, out: &mut [u8]) -> Option<Reply> {
        let n = request.len();
        if !(MIN_REQUEST..=MAX_REQUEST).contains(&n) || request[0] != 1 || request[236..240] != MAGIC {
            return None;
        }
        let rlen = reply_len(n);
        if out.len() < rlen {
            return None;
        }
        self.expire(now_ms);
        let opts = &request[240..];
        let ciaddr: [u8; 4] = request[12..16].try_into().ok()?;
        let giaddr: [u8; 4] = request[24..28].try_into().ok()?;
        let mac: [u8; 6] = request[28..34].try_into().ok()?;

        // INFORM never touches the lease table.
        let first_type = Options { rest: opts }.find(|&(c, d)| c == OPT_MSG_TYPE && !d.is_empty()).map(|(_, d)| d[0]);
        let (state, client) = if first_type == Some(INFORM) {
            if ciaddr == [0; 4] || !state_cmp_net(be(ciaddr), self.server, self.mask) {
                return None;
            }
            (State::InformAck, 0)
        } else {
            self.allocate(opts, ciaddr, mac, now_ms)
        };
        self.evict_oldest(now_ms);

        let (kind, include_lease) = match state {
            State::Offer => (ReplyKind::Offer, true),
            State::Ack => (ReplyKind::Ack, true),
            State::Nak => (ReplyKind::Nak, false),
            State::InformAck => (ReplyKind::InformAck, false),
            State::Idle | State::Release | State::Decline => return None,
        };
        out[..n].copy_from_slice(request);
        out[n..rlen].fill(0);
        out[0] = 2; // op: BOOTREPLY
        out[1] = 1;
        out[2] = 6;
        let yiaddr = if kind == ReplyKind::InformAck { [0; 4] } else { client.to_be_bytes() };
        out[16..20].copy_from_slice(&yiaddr);
        out[236..240].copy_from_slice(&MAGIC);
        let mut w = Writer { buf: &mut out[240..rlen], pos: 0 };
        self.options(&mut w, kind, include_lease)?;

        let dest = match kind {
            ReplyKind::Nak => {
                if giaddr != [0; 4] {
                    Dest::Unicast { ip: giaddr, mac }
                } else {
                    Dest::Broadcast
                }
            }
            _ => {
                if giaddr != [0; 4] {
                    Dest::Unicast { ip: giaddr, mac }
                } else if ciaddr != [0; 4] {
                    Dest::Unicast { ip: ciaddr, mac }
                } else if request[10] & 0x80 == 0 {
                    Dest::Unicast { ip: yiaddr, mac }
                } else {
                    Dest::Broadcast
                }
            }
        };
        Some(Reply { len: rlen, dest, kind, yiaddr, mac })
    }

    /// lwIP `parse_msg` after the INFORM check: find or create the client's lease, then decide the state from the options.
    fn allocate(&mut self, opts: &[u8], ciaddr: [u8; 4], mac: [u8; 6], now_ms: u32) -> (State, u32) {
        let lease_expiry = now_ms.wrapping_add(self.lease_ms);
        let mut first = self.pool_start;
        let mut client = self.plus;
        let mut renew = false;
        let mut pnode: Option<usize> = None;
        let mut matched = false;

        if self.n > 0 {
            self.declined = false;
            let mut flag = false;
            for i in 0..self.n {
                let l = self.leases[i];
                if l.mac == mac {
                    renew = l.ip.to_be_bytes() == ciaddr;
                    client = l.ip;
                    self.leases[i].expires = lease_expiry;
                    pnode = Some(i);
                    matched = true;
                    break;
                } else if l.ip == self.plus {
                    self.plus = self.plus.wrapping_add(1);
                    client = self.plus;
                }
                if !flag {
                    if first < l.ip {
                        flag = true;
                    } else {
                        first = first.wrapping_add(1);
                    }
                }
            }
        } else if self.declined {
            self.declined = false;
        } else {
            client = self.pool_start;
        }

        if !matched {
            if self.plus > self.pool_end {
                client = first;
            }
            if client > self.pool_end {
                self.plus = self.pool_start;
            } else {
                let at = self.insert(Lease { ip: client, mac, expires: lease_expiry });
                pnode = Some(at);
                self.plus = if client == self.pool_end { self.pool_start } else { client + 1 };
            }
        }

        if client > self.pool_end || client == 0 {
            if let Some(i) = pnode {
                self.remove(i);
            }
            return (State::Nak, client);
        }

        // parse_options
        let mut msg_type = 0u8;
        let mut st = State::Idle;
        for (code, d) in (Options { rest: opts }) {
            match code {
                OPT_MSG_TYPE if !d.is_empty() => msg_type = d[0],
                OPT_REQ_IP if d.len() >= 4 => {
                    st = if d[..4] == client.to_be_bytes() { State::Ack } else { State::Nak };
                }
                _ => {}
            }
        }
        match msg_type {
            DISCOVER => st = State::Offer,
            REQUEST => {
                if st != State::Ack && st != State::Nak {
                    st = if renew { State::Ack } else { State::Nak };
                }
            }
            DECLINE => st = State::Decline,
            RELEASE => st = State::Release,
            _ => {}
        }
        let mut client = client;
        if matches!(st, State::Release | State::Nak | State::Decline) {
            if let Some(i) = pnode {
                self.remove(i);
            }
            if st == State::Decline {
                self.declined = true;
            }
            client = 0;
        }
        (st, client)
    }

    /// add_msg_type + add_offer_options (or only the type for a NAK) + END.
    fn options(&self, w: &mut Writer<'_>, kind: ReplyKind, include_lease: bool) -> Option<()> {
        let t = match kind {
            ReplyKind::Offer => 2,
            ReplyKind::Ack | ReplyKind::InformAck => 5,
            ReplyKind::Nak => 6,
        };
        w.opt(OPT_MSG_TYPE, &[t])?;
        if kind != ReplyKind::Nak {
            w.opt(1, &self.cfg.netmask)?;
            if include_lease {
                w.opt(51, &self.cfg.lease_secs.to_be_bytes())?;
            }
            w.opt(54, &self.cfg.server_ip)?;
            if let Some(r) = self.cfg.router.filter(|r| *r != [0; 4]) {
                w.opt(3, &r)?;
            }
            let mut dns = [0u8; 8];
            dns[..4].copy_from_slice(&self.cfg.dns);
            match self.cfg.dns_backup.filter(|d| *d != [0; 4]) {
                Some(b) => {
                    dns[4..].copy_from_slice(&b);
                    w.opt(6, &dns)?;
                }
                None => w.opt(6, &dns[..4])?,
            }
            w.opt(28, &((self.server & self.mask) | !self.mask).to_be_bytes())?;
            w.opt(26, &[0x05, 0xdc])?;
            w.opt(31, &[0])?;
            w.opt(43, &[1, 4, 0, 0, 0, 2])?;
        }
        w.put(&[OPT_END])
    }
}
