#![allow(dead_code)]
use std::collections::HashMap;
use tdongle_tailnet_types::Key32;

pub fn unhex(s: &str) -> Vec<u8> {
    (0..s.len() / 2).map(|i| u8::from_str_radix(&s[2 * i..2 * i + 2], 16).unwrap()).collect()
}

pub fn key(b: &[u8]) -> Key32 {
    let mut k = Key32::ZERO;
    k.0.copy_from_slice(b);
    k
}

/// The vectors generated by Tailscale's own `controlbase` code (see tests/vectors/gen_vectors_test.go.txt).
pub fn vectors() -> HashMap<String, Vec<u8>> {
    let text = include_str!("../vectors/tailscale_controlbase_v1.104.0.txt");
    text.lines().filter_map(|l| l.split_once('=')).map(|(k, v)| (k.to_string(), unhex(v))).collect()
}

/// `byte(i * mul)` fill used by the Go generator.
pub fn pattern(len: usize, mul: usize) -> Vec<u8> {
    (0..len).map(|i| (i * mul) as u8).collect()
}

/// Plaintexts of the five records, in order: hello, 4077 bytes, first 4077 of 5000, the remaining 923, "x".
pub fn record_plaintexts() -> [Vec<u8>; 5] {
    let p2 = pattern(5000, 13);
    [b"hello".to_vec(), pattern(4077, 7), p2[..4077].to_vec(), p2[4077..].to_vec(), b"x".to_vec()]
}

use tdongle_tailnet_noise::{Initiator, Session, responder};
use tdongle_tailnet_types::Entropy;
use tdongle_tailnet_types::test_util::TestRng;

/// A deterministic handshake: returns (client, server) sessions.
pub fn pair(seed: u64, version: u16) -> (Session, Session) {
    let mut rng = TestRng(seed | 1);
    let mpriv = tdongle_tailnet_crypto::x25519::generate(&mut rng);
    let cpriv = tdongle_tailnet_crypto::x25519::generate(&mut rng);
    let cpub = tdongle_tailnet_crypto::x25519::public(&cpriv);
    let (init, msg1) = Initiator::new(&mpriv, &cpub, version, &mut rng).unwrap();
    let acc = responder::accept(&cpriv, &msg1, &mut rng).unwrap();
    let client = init.finish(&acc.response).unwrap();
    (client, acc.session)
}

pub fn rand_bytes(rng: &mut dyn Entropy, n: usize) -> Vec<u8> {
    let mut v = vec![0u8; n];
    rng.fill(&mut v);
    v
}
